# Generated by Django 2.2 on 2020-06-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20200604_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('p', 'pop'), ('r', 'rock'), ('c', 'classic')], default='p', max_length=100),
            preserve_default=False,
        ),
    ]
